import {api,fetchWorkspace,searchWorkspace,syncMeta,ApiError} from './api-client.js';
import {$,$$,arr,esc,nl2br,fmt,fmtTime,initials,isPast,icon,toast,setLoading,setOffline,fileToBase64,downloadCsv,downloadIcs,copyText,parseCsv,applyTheme,initBrandAssets} from './ui.js';

const state={data:{},meta:{revisions:{}},view:'home',commFilter:'all',docFilter:'all',decisionFilter:'active',courseFilter:'all',opsTab:'incidents',adminTab:'overview',adminUsers:[],resetRequests:[],analytics:null,searchResults:[],dirty:false,editor:null,adminUsersSelected:new Set()};
const TITLES={home:['CENTRALIZED CALL CENTER','Home'],communications:['TEAM SIGNAL','Communications'],knowledge:['TRUSTED KNOWLEDGE','Knowledge'],learning:['TEAM LEARNING','Learning'],operations:['LIVE OPERATIONS','Operations'],decisions:['DURABLE CONTEXT','Decisions'],admin:['MANAGE THE HUB','Admin'],search:['SEARCH','Results']};
const COLLECTION_VIEW={updates:'communications',docs:'knowledge',decisions:'decisions',incidents:'operations',handoffs:'operations',roster:'operations'};
const canEdit=()=>['editor','admin'].includes(state.data.me?.role);const isAdmin=()=>state.data.me?.role==='admin';
const find=(collection,id)=>arr(state.data[collection]).find(x=>x.id===id);
function upsert(collection,item){const list=arr(state.data[collection]);const i=list.findIndex(x=>x.id===item.id);if(i>=0)list[i]=item;else list.unshift(item);state.data[collection]=list;}
function remove(collection,id){state.data[collection]=arr(state.data[collection]).filter(x=>x.id!==id);}

function showAuth(panel='login'){$('#authScreen').classList.remove('hidden');$('#appShell').classList.add('hidden');['login','signup','reset','resetToken','verify','mfa'].forEach(name=>$(`#${name}Panel`)?.classList.toggle('hidden',name!==panel));}
function showApp(){
  $('#authScreen').classList.add('hidden');$('#appShell').classList.remove('hidden');
  $('#profileInitial').textContent=initials(state.data.me?.name);$('#profileName').textContent=state.data.me?.name||'User';$('#profileRole').textContent=(state.data.me?.role||'viewer').replace(/^./,c=>c.toUpperCase());
  $('#adminNav').classList.toggle('hidden',!isAdmin());$$('.editor-only').forEach(el=>el.classList.toggle('hidden',!canEdit()));renderAll();
}

async function bootstrap({quiet=false}={}){
  try{if(!quiet)setLoading(true,'Loading workspace…');const out=await fetchWorkspace('updates,docs,groups,courses,resources,attachments,incidents,handoffs,roster,progress,notifications,me');state.data=out.data||{};state.meta=out.meta||{};showApp();setOffline(false);return true;}
  catch(error){if(error.status===401){showAuth('login');return false;}if(error.code==='NETWORK'){setOffline(true);if(!quiet)toast(error.message,'error');return false;}toast(error.message||'Unable to load the workspace.','error');return false;}
  finally{if(!quiet)setLoading(false);}
}
async function refresh(scope='all',{quiet=true}={}){try{const out=await fetchWorkspace(scope);Object.assign(state.data,out.data||{});state.meta=out.meta||state.meta;if(!quiet)toast('Workspace refreshed.','success');renderAll();}catch(error){if(error.code==='NETWORK')setOffline(true);else toast(error.message,'error');}}

function setView(view){
  state.view=view;$$('.view').forEach(el=>el.classList.toggle('active',el.id===`${view}View`));$$('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.view===view));
  const [eye,title]=TITLES[view]||['CENTRALIZED CALL CENTER',view];$('#viewEyebrow').textContent=eye;$('#viewTitle').textContent=title;$('#notificationPanel').classList.add('hidden');$('#profilePanel').classList.add('hidden');
  if(view==='admin'){ensureAdminData().then(()=>renderAdmin());renderAdmin();}if(view==='decisions'&&!('decisions' in state.data))refresh('decisions',{quiet:true});if(view==='operations')renderOperations();if(view==='search')renderSearch();$('#mainContent').focus({preventScroll:true});
}

const pill=(text,cls='')=>`<span class="pill ${esc(cls||text)}">${esc(text)}</span>`;
const empty=(text)=>`<div class="empty-state"><strong>Nothing here yet.</strong><p>${esc(text)}</p></div>`;
function listRow(title,sub,attrs='',right=''){return `<button type="button" class="list-row clickable" ${attrs}><span><strong>${esc(title)}</strong><small>${esc(sub)}</small></span><span>${right}</span></button>`;}

function renderAll(){renderNotifications();renderHome();renderCommunications();renderKnowledge();renderLearning();renderOperations();renderDecisions();if(isAdmin())renderAdmin();renderProfile();setupReveal();}
function renderHome(){
  const updates=arr(state.data.updates).filter(x=>x.status==='Active'),docs=arr(state.data.docs).filter(x=>x.status==='Active'),courses=arr(state.data.courses).filter(x=>x.status==='Active'),incidents=arr(state.data.incidents).filter(x=>!['Resolved','Archived'].includes(x.status));
  const mandatoryUnread=updates.filter(u=>u.mandatory&&!arr(u.acknowledgements).some(a=>a.userId===state.data.me?.id));
  const stats=[['Active updates',updates.length],['Needs acknowledgement',mandatoryUnread.length],['Open incidents',incidents.length],['Learning assigned',courses.length]];
  $('#homeStats').innerHTML=stats.map(([label,val])=>`<article class="stat-card"><strong>${val}</strong><span>${esc(label)}</span></article>`).join('');
  const pinned=updates.filter(x=>x.pinned||['Critical'].includes(x.priority)).slice(0,5);$('#pinnedUpdates').innerHTML=pinned.length?pinned.map(x=>listRow(x.title,x.summary,`data-open="updates" data-id="${x.id}"`,pill(x.priority))).join(''):empty('Pinned and critical communications will appear here.');
  $('#homeOperations').innerHTML=incidents.slice(0,5).map(x=>listRow(x.title,`${x.severity} · ${x.status}`,`data-open="incidents" data-id="${x.id}"`,pill(x.severity))).join('')||empty('No active high-priority incidents.');
  $('#homeLearning').innerHTML=courses.slice(0,5).map(c=>{const p=c.progress||{};return listRow(c.title,`${p.percent||0}% complete${c.dueDate?` · due ${fmt(c.dueDate)}`:''}`,`data-course="${c.id}"`,pill(p.completed?'Complete':isPast(c.dueDate)?'Overdue':'Assigned',p.completed?'approved':isPast(c.dueDate)?'critical':''));}).join('')||empty('No learning assigned right now.');
  $('#attentionList').innerHTML=arr(state.data.notifications).slice(0,6).map(n=>listRow(n.title,n.text,`data-notification="${esc(n.id)}" data-view="${esc(n.view)}" data-item="${esc(n.itemId||'')}"`,pill(n.priority||'Normal'))).join('')||empty('You are all caught up.');
  const recent=[...docs].sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt))).slice(0,3);$('#recentKnowledge').innerHTML=recent.map(doc=>knowledgeCard(doc)).join('')||empty('Knowledge items will appear here.');
}

function renderNotifications(){const list=arr(state.data.notifications);$('#notificationBadge').textContent=String(list.length);$('#notificationBadge').classList.toggle('hidden',!list.length);$('#notificationButton').setAttribute('aria-label',`Notifications, ${list.length} unread`);$('#notificationList').innerHTML=list.length?list.map(n=>`<button type="button" class="notification-item" data-notification="${esc(n.id)}" data-view="${esc(n.view)}" data-item="${esc(n.itemId||'')}"><span>${pill(n.priority||'Normal')}</span><strong>${esc(n.title)}</strong><small>${esc(n.text)}</small></button>`).join(''):empty('No unread notifications.');}
function isAcked(update){return arr(update.acknowledgements).some(a=>a.userId===state.data.me?.id);}
function commCard(item){const archived=item.status==='Archived';return `<article class="comm-card ${archived?'is-archived':''}"><label class="select-box editor-only ${canEdit()?'':'hidden'}"><input type="checkbox" data-select-comm="${item.id}"><span class="sr-only">Select ${esc(item.title)}</span></label><div class="comm-date"><span>${fmt(item.createdAt)}</span>${isAcked(item)?pill('Read','approved'):item.mandatory?pill('Unread','pending'):''}</div><button class="comm-main" data-open="updates" data-id="${item.id}"><small>${esc(item.category||'Announcement')} · Owner: ${esc(item.owner||'—')}</small><strong>${esc(item.title)}</strong><p>${esc(item.summary||'')}</p></button><div>${pill(item.priority||'Medium')}${archived?pill('Archived','archived'):''}</div></article>`;}
function renderCommunications(){let list=arr(state.data.updates);const f=state.commFilter;if(f==='mandatory')list=list.filter(x=>x.mandatory);else if(f==='unread')list=list.filter(x=>x.mandatory&&!isAcked(x));else if(f==='Archived')list=list.filter(x=>x.status==='Archived');else if(f!=='all')list=list.filter(x=>x.priority===f);else list=list.filter(x=>x.status!=='Archived');$('#communicationsList').innerHTML=list.length?list.map(commCard).join(''):empty('No communications match this filter.');}
function knowledgeCard(doc){return `<article class="knowledge-card ${doc.status==='Archived'?'is-archived':''}"><div class="card-top"><label class="select-box editor-only ${canEdit()?'':'hidden'}"><input type="checkbox" data-select-doc="${doc.id}"><span class="sr-only">Select ${esc(doc.title)}</span></label>${pill(doc.type||'Reference')} ${doc.status==='Archived'?pill('Archived','archived'):''}</div><button type="button" class="card-button" data-open="docs" data-id="${doc.id}"><h3>${esc(doc.title)}</h3><p>${esc(doc.summary||'')}</p><small>v${Number(doc.version||1)} · Owner ${esc(doc.owner||'—')}${doc.reviewDate?` · review ${fmt(doc.reviewDate)}`:''}</small></button>${doc.type==='Macro'?`<button class="btn ghost compact" data-copy-macro="${doc.id}">${icon('copy')} Copy response</button>`:''}</article>`;}
function renderKnowledge(){let list=arr(state.data.docs);if(state.docFilter==='Archived')list=list.filter(x=>x.status==='Archived');else if(state.docFilter!=='all')list=list.filter(x=>x.type===state.docFilter&&x.status!=='Archived');else list=list.filter(x=>x.status!=='Archived');$('#knowledgeList').innerHTML=list.length?list.map(knowledgeCard).join(''):empty('No knowledge items match this filter.');}
function renderLearning(){let list=arr(state.data.courses);if(!isAdmin())list=list.filter(x=>x.status==='Active');const f=state.courseFilter;if(f==='complete')list=list.filter(x=>x.progress?.completed);if(f==='overdue')list=list.filter(x=>!x.progress?.completed&&isPast(x.dueDate));if(f==='inprogress')list=list.filter(x=>(x.progress?.percent||0)>0&&!x.progress?.completed);const total=list.length?Math.round(list.reduce((s,c)=>s+(c.progress?.percent||0),0)/list.length):0;$('#learningOverall').textContent=`${total}%`;$('#courseGrid').innerHTML=list.length?list.map(c=>`<article class="course-card"><div class="course-cover">${c.coverUrl?`<img src="${esc(c.coverUrl)}" alt="">`:`${icon('learn')}`}</div><div class="course-body"><div>${c.required?pill('Required','pending'):pill('Optional')} ${isPast(c.dueDate)&&!c.progress?.completed?pill('Overdue','critical'):''}</div><h3>${esc(c.title)}</h3><p>${esc(c.description||'')}</p><div class="progress-track"><span style="width:${Math.max(0,Math.min(100,c.progress?.percent||0))}%"></span></div><small>${c.progress?.percent||0}% complete${c.dueDate?` · due ${fmt(c.dueDate)}`:''}</small><button class="btn primary" data-course="${c.id}">${c.progress?.completed?'Review course':'Open course'}</button></div></article>`).join(''):empty('No assigned courses match this filter.');}
function renderDecisions(){let list=arr(state.data.decisions);if(state.decisionFilter==='active')list=list.filter(x=>x.status!=='Archived');else if(state.decisionFilter==='Archived')list=list.filter(x=>x.status==='Archived');$('#decisionList').innerHTML=list.length?list.map(x=>`<article class="decision-card"><button data-open="decisions" data-id="${x.id}"><small>${fmt(x.createdAt)} · Owner ${esc(x.owner||'—')}</small><strong>${esc(x.decision||'Decision')}</strong><p>${esc(x.impact||x.reason||'')}</p></button>${x.status==='Archived'?pill('Archived','archived'):''}</article>`).join(''):empty('No decisions have been recorded.');}

function renderOperations(){
  const tab=state.opsTab;$$('#operationsTabs .chip').forEach(b=>b.classList.toggle('active',b.dataset.opsTab===tab));$('#opsCreateButton').textContent=tab==='incidents'?'+ New incident':tab==='handoffs'?'+ New handoff':'+ Roster entry';$('#opsCreateButton').classList.toggle('hidden',!canEdit()||(tab==='roster'&&!isAdmin()));
  if(tab==='incidents'){const list=arr(state.data.incidents).filter(x=>x.status!=='Archived');$('#operationsContent').innerHTML=`<div class="ops-board">${list.length?list.map(x=>`<article class="ops-card severity-${String(x.severity||'medium').toLowerCase()}"><div>${pill(x.severity||'Medium')} ${pill(x.status||'Open')}</div><button data-open="incidents" data-id="${x.id}"><h3>${esc(x.title)}</h3><p>${esc(x.summary||'')}</p><small>Owner ${esc(x.owner||'—')}${x.nextAction?` · Next: ${esc(x.nextAction)}`:''}</small></button></article>`).join(''):empty('No active incidents.')}</div>`;}
  if(tab==='handoffs'){const list=arr(state.data.handoffs).filter(x=>x.status!=='Archived');$('#operationsContent').innerHTML=`<div class="stack">${list.length?list.map(x=>`<article class="handoff-card"><button data-open="handoffs" data-id="${x.id}"><small>${fmt(x.shiftDate)} · ${esc(x.shiftName||'Shift')}</small><strong>${esc(x.summary||'Shift handoff')}</strong><p>${esc(x.outstanding||x.priorities||'')}</p></button></article>`).join(''):empty('No shift handoffs yet.')}</div>`;}
  if(tab==='roster'){const list=arr(state.data.roster).filter(x=>x.status!=='Archived');$('#operationsContent').innerHTML=`<div class="section-card"><div class="table-wrap"><table><thead><tr><th>Name</th><th>Role</th><th>Starts</th><th>Ends</th><th>Notes</th></tr></thead><tbody>${list.map(x=>`<tr data-open="roster" data-id="${x.id}"><td>${esc(x.name)}</td><td>${esc(x.role||'On call')}</td><td>${fmtTime(x.startAt)}</td><td>${fmtTime(x.endAt)}</td><td>${esc(x.notes||'')}</td></tr>`).join('')}</tbody></table></div>${!list.length?empty('No roster entries.') : ''}</div>`;}
}

function renderProfile(){$('#profileInfo').innerHTML=`<div class="profile-summary"><span class="avatar">${esc(initials(state.data.me?.name))}</span><h3>${esc(state.data.me?.name||'')}</h3><p>${esc(state.data.me?.email||'')}</p>${pill((state.data.me?.role||'viewer').toUpperCase())}<small>${state.data.me?.emailVerified?'Email verified':'Email verification pending'} · ${state.data.me?.mfaEnabled?'MFA enabled':'MFA not enabled'}</small></div>`;}

function renderSearch(){const results=arr(state.searchResults);$('#searchCount').textContent=`${results.length} found`;$('#searchResults').innerHTML=results.length?results.map(r=>`<button class="search-result" data-search-open="${esc(r.view)}" data-id="${esc(r.itemId)}" data-type="${esc(r.type)}"><span>${pill(r.type)}</span><strong>${highlight(r.title,state.searchQuery)}</strong><p>${highlight(r.snippet||'',state.searchQuery)}</p></button>`).join(''):empty('Try a different search term.');}

function renderAdmin(){if(!isAdmin())return;$$('#adminTabs .chip').forEach(b=>b.classList.toggle('active',b.dataset.adminTab===state.adminTab));const target=$('#adminContent');
  if(state.adminTab==='overview'){const pending=[...arr(state.data.updates),...arr(state.data.docs),...arr(state.data.decisions)].filter(x=>x.approvalStatus==='pending');target.innerHTML=`<div class="stats-grid"><article class="stat-card"><strong>${state.adminUsers.length||'—'}</strong><span>Users</span></article><article class="stat-card"><strong>${pending.length}</strong><span>Approvals</span></article><article class="stat-card"><strong>${arr(state.data.resources).length}</strong><span>Learning resources</span></article><article class="stat-card"><strong>${arr(state.data.incidents).filter(x=>!['Resolved','Archived'].includes(x.status)).length}</strong><span>Open incidents</span></article></div><div class="section-card"><h3>Administration</h3><p>Manage access, approvals, learning, Call Center groups, compliance reporting, and the audit trail from the tabs above.</p></div>`;return;}
  if(state.adminTab==='users'){renderAdminUsers();return;}if(state.adminTab==='groups'){renderGroups();return;}if(state.adminTab==='approvals'){renderApprovals();return;}if(state.adminTab==='learning'){renderLearningAdmin();return;}if(state.adminTab==='reports'){renderReports();return;}if(state.adminTab==='audit'){renderAudit();}
}
async function loadAdminUsers(){if(!isAdmin())return;try{const out=await api('admin/users');state.adminUsers=out.users||[];state.resetRequests=out.resetRequests||[];}catch(e){toast(e.message,'error');}}
async function ensureAdminData(){if(!isAdmin())return;if(!state.adminUsers.length)await loadAdminUsers();const need=['decisions','quizzes','questionBank','activity'].filter(k=>!(k in state.data));if(need.length)await refresh(need.join(','),{quiet:true});}
function renderAdminUsers(){const target=$('#adminContent');target.innerHTML=`<div class="section-card"><div class="section-heading"><div><h3>User management</h3><p class="muted">New users default to Viewer. Promote only when needed.</p></div><div class="tool-actions"><label class="btn ghost file-button">Import CSV<input type="file" id="userCsv" accept=".csv,text/csv" hidden></label><button class="btn ghost" data-bulk-user="role">Bulk role</button><button class="btn ghost" data-bulk-user="groups">Bulk groups</button></div></div><div class="table-wrap"><table><thead><tr><th></th><th>User</th><th>Status</th><th>Role</th><th>Groups</th><th>Last login</th><th>Actions</th></tr></thead><tbody>${state.adminUsers.map(u=>`<tr><td><input type="checkbox" data-admin-user-select="${u.id}" ${state.adminUsersSelected.has(u.id)?'checked':''}></td><td><strong>${esc(u.name)}</strong><small>${esc(u.email)}</small></td><td>${pill(u.status||'pending')}</td><td><select data-user-role="${u.id}"><option value="viewer" ${u.role==='viewer'?'selected':''}>Viewer</option><option value="editor" ${u.role==='editor'?'selected':''}>Editor</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select></td><td>${arr(u.groupIds).map(id=>esc(find('groups',id)?.name||id)).join(', ')||'—'}</td><td>${fmtTime(u.lastLoginAt)}</td><td><div class="row-actions">${!u.emailVerified?`<button class="small-btn" data-user-action="verify-email" data-id="${u.id}">Verify email</button>`:''}<button class="small-btn" data-user-groups="${u.id}">Groups</button><button class="small-btn" data-user-reset="${u.id}">Reset</button><button class="small-btn" data-user-status="${u.id}">${u.status==='active'?'Suspend':'Activate'}</button></div></td></tr>`).join('')}</tbody></table></div></div>`;}
function renderGroups(){const list=arr(state.data.groups);$('#adminContent').innerHTML=`<div class="section-card"><div class="section-heading"><div><h3>Centralized Call Center groups</h3><p class="muted">Used only to target communications and learning inside this team.</p></div><button class="btn primary" data-new-group>+ New group</button></div><div class="card-grid compact">${list.map(g=>`<article class="knowledge-card"><h3>${esc(g.name)}</h3><p>${esc(g.description||'')}</p><div class="row-actions"><button class="small-btn" data-edit-group="${g.id}">Edit</button><button class="small-btn danger-outline" data-delete-group="${g.id}">Delete</button></div></article>`).join('')||empty('Create a group when you need targeted assignments.')}</div></div>`;}
function renderApprovals(){const pending=[...arr(state.data.updates).map(x=>({...x,_c:'updates'})),...arr(state.data.docs).map(x=>({...x,_c:'docs'})),...arr(state.data.decisions).map(x=>({...x,_c:'decisions'}))].filter(x=>x.approvalStatus==='pending');$('#adminContent').innerHTML=`<div class="section-card"><h3>Content approvals</h3><div class="stack">${pending.length?pending.map(x=>`<article class="approval-row"><div><strong>${esc(x.title||x.decision)}</strong><small>${esc(x.owner||'')} · ${esc(x._c)}</small></div><div class="row-actions"><button class="btn ghost compact" data-approve="rejected" data-collection="${x._c}" data-id="${x.id}">Reject</button><button class="btn primary compact" data-approve="approved" data-collection="${x._c}" data-id="${x.id}">Approve</button></div></article>`).join(''):empty('No content is waiting for approval.')}</div></div>`;}
function resourceCard(r){const archived=r.status==='Archived',drive=r.sourceType==='google-drive';const label=drive?'Google Drive':`${esc(r.fileName||'File')} · ${Math.ceil((r.size||0)/1024)} KB`;return `<article class="resource-card ${archived?'is-archived':''}"><div class="resource-icon">${drive?'DRIVE':esc((r.fileName||'FILE').split('.').pop().toUpperCase().slice(0,5))}</div><div class="resource-main"><div class="resource-title-row"><strong>${esc(r.title)}</strong>${pill(`v${r.version||1}`)}${drive?pill('Drive','approved'):''}${archived?pill('Archived','archived'):''}</div><small>${label} · ${esc(r.category||'General')}</small><p class="resource-description">${esc(r.description||'')}</p></div><div class="resource-actions"><button class="small-btn" data-resource-open="${r.id}">Open</button><button class="small-btn" data-resource-edit="${r.id}">Edit</button>${drive?'':`<button class="small-btn" data-resource-replace="${r.id}">Replace</button>`}${archived?`<button class="small-btn" data-resource-action="restore" data-id="${r.id}">Restore</button>`:`<button class="small-btn" data-resource-action="archive" data-id="${r.id}">Archive</button>`}<button class="small-btn danger-outline" data-resource-action="delete" data-id="${r.id}">Delete</button></div></article>`;}
function renderLearningAdmin(){const active=arr(state.data.resources).filter(r=>r.status!=='Archived'),arch=arr(state.data.resources).filter(r=>r.status==='Archived');$('#adminContent').innerHTML=`<div class="section-card content-library"><div class="section-heading"><div><h3>Content Library</h3><p class="muted">Upload, replace, archive, and remove learning resources.</p></div><div class="tool-actions"><button class="btn ghost" data-resource-drive>+ Add from Google Drive</button><button class="btn primary" data-resource-upload>+ Upload small file</button></div></div><div class="resource-list">${active.map(resourceCard).join('')||empty('Upload your first learning document.')}</div><details class="archive-drawer"><summary>Archived content (${arch.length})</summary><div class="resource-list">${arch.map(resourceCard).join('')||'<p class="muted">Nothing archived.</p>'}</div></details></div><div class="section-card"><div class="section-heading"><h3>Courses</h3><button class="btn primary" data-course-admin>+ Create course</button></div><div class="card-grid compact">${arr(state.data.courses).map(c=>`<article class="knowledge-card"><div>${pill(c.status||'Active')} ${c.required?pill('Required','pending'):''}</div><h3>${esc(c.title)}</h3><p>${esc(c.description||'')}</p><button class="small-btn" data-course-admin="${c.id}">Edit course</button></article>`).join('')||empty('No courses yet.')}</div></div><div class="section-card"><div class="section-heading"><h3>Quizzes & question bank</h3><div class="tool-actions"><button class="btn ghost" data-question-admin>+ Question</button><button class="btn primary" data-quiz-admin>+ Quiz</button></div></div><p class="muted">${arr(state.data.questionBank).length} questions · ${arr(state.data.quizzes).length} quizzes</p></div>`;}
function renderReports(){if(!state.analytics){$('#adminContent').innerHTML=`<div class="section-card"><h3>Reports</h3><p>Load current learning, acknowledgement, quiz, resource-open, and incident analytics.</p><button class="btn primary" data-load-reports>Load reports</button></div>`;return;}const a=state.analytics;$('#adminContent').innerHTML=`<div class="stats-grid"><article class="stat-card"><strong>${a.learning.filter(x=>x.completed).length}</strong><span>Course completions</span></article><article class="stat-card"><strong>${a.learning.filter(x=>x.overdue).length}</strong><span>Overdue assignments</span></article><article class="stat-card"><strong>${a.acknowledgements.filter(x=>!x.acknowledged).length}</strong><span>Missing acknowledgements</span></article><article class="stat-card"><strong>${a.quizAttempts.length}</strong><span>Quiz attempts</span></article></div><div class="section-card"><h3>Exports</h3><div class="tool-actions"><button class="btn ghost" data-export-report="learning">Learning CSV</button><button class="btn ghost" data-export-report="acknowledgements">Acknowledgements CSV</button><button class="btn ghost" data-export-report="quizAttempts">Quiz results CSV</button><button class="btn ghost" data-export-report="resourceOpens">Document opens CSV</button><button class="btn ghost" data-export-report="incidents">Incidents CSV</button></div></div>`;}
function renderAudit(){$('#adminContent').innerHTML=`<div class="section-card"><h3>Audit trail</h3><div class="stack">${arr(state.data.activity).slice(0,250).map(a=>`<div class="history-item"><strong>${esc(a.actor)} · ${esc(a.action)}</strong><span>${esc(a.collection)} · ${esc(a.label)}</span><small>${fmtTime(a.at)}${a.detail?` · ${esc(a.detail)}`:''}</small></div>`).join('')||empty('Audit activity will appear here.')}</div></div>`;}

function setupReveal(){requestAnimationFrame(()=>$$('.reveal').forEach(el=>el.classList.add('revealed')));}

// ---------- Detail views ----------
function attachmentsHtml(item){const ids=arr(item.attachmentIds);if(!ids.length)return '';return `<section class="detail-section"><h3>Attachments</h3><div class="attachment-list">${ids.map(id=>{const a=find('attachments',id);return a?`<a class="attachment-link" href="/api/files/open?id=${encodeURIComponent(id)}" target="_blank" rel="noopener">${icon('download')}<span>${esc(a.title||a.fileName)}</span><small>${Math.ceil((a.size||0)/1024)} KB</small></a>`:'';}).join('')}</div></section>`;}
function openItem(collection,id){const item=find(collection,id);if(!item)return toast('Item not found.','error');if(collection==='incidents'||collection==='handoffs'||collection==='roster')return openOpsDetail(collection,item);let html='';
  if(collection==='updates'){html=`<span class="eyebrow">${esc(item.category||'COMMUNICATION')}</span><h2>${esc(item.title)}</h2><div class="detail-meta">${pill(item.priority||'Medium')} ${pill(item.status||'Active')} ${item.mandatory?pill('Acknowledgement required','pending'):''} ${item.pinned?pill('Pinned'):''}</div><p class="lead">${esc(item.summary||'')}</p><div class="rich-copy">${nl2br(item.details||'')}</div>${attachmentsHtml(item)}<div class="detail-grid"><div><small>Owner</small><strong>${esc(item.owner||'—')}</strong></div><div><small>Updated</small><strong>${fmtTime(item.updatedAt)}</strong></div><div><small>Review</small><strong>${fmt(item.reviewDate)}</strong></div><div><small>Acknowledgements</small><strong>${arr(item.acknowledgements).length}</strong></div></div><div class="modal-actions">${item.mandatory&&!isAcked(item)?`<button class="btn primary" data-ack="${item.id}">I've read and understood</button>`:''}${canEdit()?`<button class="btn ghost" data-edit="updates" data-id="${item.id}">Edit</button><button class="btn ghost" data-archive="updates" data-id="${item.id}">${item.status==='Archived'?'Restore':'Archive'}</button>`:''}${isAdmin()?`<button class="btn danger" data-permanent-delete="${item.id}">Delete permanently</button>`:''}</div>`;}
  if(collection==='docs'){html=`<span class="eyebrow">${esc(item.type||'KNOWLEDGE')}</span><h2>${esc(item.title)}</h2><div class="detail-meta">${pill(`v${item.version||1}`)} ${pill(item.status||'Active')} ${arr(item.outdatedFlags).some(f=>!f.resolved)?pill('Flagged outdated','critical'):''}</div><p class="lead">${esc(item.summary||'')}</p><div class="rich-copy knowledge-copy">${nl2br(item.content||'')}</div>${item.type==='Macro'?`<button class="btn primary" data-copy-macro="${item.id}">${icon('copy')} Copy response</button>`:''}${attachmentsHtml(item)}<section class="detail-section"><h3>Feedback</h3><form data-doc-feedback="comment" data-id="${item.id}" class="inline-form"><input name="text" placeholder="Add a comment…" required><button class="btn ghost">Comment</button></form><form data-doc-feedback="flag" data-id="${item.id}" class="inline-form"><input name="text" placeholder="What looks outdated?" required><button class="btn ghost">Flag as outdated</button></form><div class="feedback-list">${[...arr(item.comments),...arr(item.outdatedFlags)].sort((a,b)=>String(b.at).localeCompare(String(a.at))).map(f=>`<div class="history-item ${f.resolved?'resolved':''}"><strong>${esc(f.name)}</strong><span>${esc(f.text)}</span><small>${fmtTime(f.at)}${f.resolved?' · resolved':''}</small>${canEdit()&&!f.resolved?`<button class="small-btn" data-resolve-feedback="${f.id}" data-doc="${item.id}">Resolve</button>`:''}</div>`).join('')}</div></section><div class="modal-actions">${canEdit()?`<button class="btn ghost" data-edit="docs" data-id="${item.id}">Edit</button><button class="btn ghost" data-archive="docs" data-id="${item.id}">${item.status==='Archived'?'Restore':'Archive'}</button>`:''}</div>`;}
  if(collection==='decisions'){html=`<span class="eyebrow">DECISION</span><h2>${esc(item.decision)}</h2><section class="detail-section"><h3>Reason</h3><div class="rich-copy">${nl2br(item.reason||'')}</div></section><section class="detail-section"><h3>Impact</h3><div class="rich-copy">${nl2br(item.impact||'')}</div></section><div class="detail-grid"><div><small>Owner</small><strong>${esc(item.owner||'—')}</strong></div><div><small>Review</small><strong>${fmt(item.reviewDate)}</strong></div></div><div class="modal-actions">${canEdit()?`<button class="btn ghost" data-edit="decisions" data-id="${item.id}">Edit</button><button class="btn ghost" data-archive="decisions" data-id="${item.id}">Archive</button>`:''}</div>`;}
  $('#itemModalBody').innerHTML=html;$('#itemModal').showModal();
}
function openOpsDetail(collection,item){let html;if(collection==='incidents')html=`<span class="eyebrow">INCIDENT</span><h2>${esc(item.title)}</h2><div>${pill(item.severity)} ${pill(item.status)}</div><p class="lead">${esc(item.summary||'')}</p><div class="rich-copy">${nl2br(item.details||'')}</div><section class="detail-section"><h3>Next action</h3><p>${esc(item.nextAction||'—')}</p></section>`;if(collection==='handoffs')html=`<span class="eyebrow">SHIFT HANDOFF</span><h2>${esc(item.shiftName||'Shift')}</h2><p class="lead">${esc(item.summary||'')}</p><div class="detail-grid"><div><small>Outgoing</small><strong>${esc(item.outgoing||'—')}</strong></div><div><small>Incoming</small><strong>${esc(item.incoming||'—')}</strong></div></div><section class="detail-section"><h3>Outstanding</h3><div class="rich-copy">${nl2br(item.outstanding||'')}</div><h3>Priorities</h3><div class="rich-copy">${nl2br(item.priorities||'')}</div></section>`;if(collection==='roster')html=`<span class="eyebrow">ROSTER</span><h2>${esc(item.name)}</h2><p>${esc(item.role||'On call')}</p><div class="detail-grid"><div><small>Starts</small><strong>${fmtTime(item.startAt)}</strong></div><div><small>Ends</small><strong>${fmtTime(item.endAt)}</strong></div></div><p>${esc(item.notes||'')}</p>`;html+=`<div class="modal-actions">${canEdit()&&(collection!=='roster'||isAdmin())?`<button class="btn ghost" data-edit-ops="${collection}" data-id="${item.id}">Edit</button><button class="btn danger" data-archive-ops="${collection}" data-id="${item.id}">Archive</button>`:''}</div>`;$('#itemModalBody').innerHTML=html;$('#itemModal').showModal();}

// ---------- Editors ----------
function groupChecks(selected=[]){return `<div class="group-picker"><input type="search" data-group-search placeholder="Search Call Center groups"><div class="groups-check">${arr(state.data.groups).map(g=>`<label><input type="checkbox" name="targetGroupIds" value="${g.id}" ${selected.includes(g.id)?'checked':''}><span>${esc(g.name)}</span></label>`).join('')||'<span class="muted">No groups configured. Leaving blank targets everyone.</span>'}</div></div>`;}
function field(label,input){return `<label>${label}${input}</label>`;}
function openEditor(collection,item=null){if(!canEdit())return;state.editor={collection,id:item?.id||null};state.dirty=false;$('#editorEyebrow').textContent=item?'EDIT':'NEW';$('#editorTitle').textContent=collection==='updates'?(item?'Edit communication':'Create communication'):collection==='docs'?(item?'Edit knowledge':'Create knowledge'):(item?'Edit decision':'Record decision');
  let html='';if(collection==='updates')html=[field('Title',`<input name="title" required maxlength="250" value="${esc(item?.title||'')}">`),field('Summary',`<textarea name="summary">${esc(item?.summary||'')}</textarea>`),field('Details',`<textarea name="details" class="tall">${esc(item?.details||'')}</textarea>`),`<div class="form-grid">${field('Category',`<select name="category">${['Announcement','Operational Update','Process Change','Incident Update','Customer Update','Meeting Outcome'].map(v=>`<option ${item?.category===v?'selected':''}>${v}</option>`).join('')}</select>`)}${field('Priority',`<select name="priority">${['Critical','High','Medium','Low'].map(v=>`<option ${item?.priority===v?'selected':''}>${v}</option>`).join('')}</select>`)}</div>`,field('Owner',`<input name="owner" value="${esc(item?.owner||state.data.me?.name||'')}">`),`<div class="check-row"><label><input type="checkbox" name="mandatory" ${item?.mandatory?'checked':''}> Acknowledgement required</label><label><input type="checkbox" name="pinned" ${item?.pinned?'checked':''}> Pin</label></div>`,`<div class="form-grid">${field('Review date',`<input type="date" name="reviewDate" value="${esc((item?.reviewDate||'').slice(0,10))}">`)}${field('Expires',`<input type="datetime-local" name="expiresAt" value="${esc((item?.expiresAt||'').slice(0,16))}">`)}</div>`,`<fieldset><legend>Target Call Center groups</legend>${groupChecks(arr(item?.targetGroupIds))}</fieldset>`,field('Attachments',`<input type="file" name="attachments" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.docx,.pptx,.xlsx,.mp4">`)].join('');
  if(collection==='docs')html=[field('Title',`<input name="title" required value="${esc(item?.title||'')}">`),field('Summary',`<textarea name="summary">${esc(item?.summary||'')}</textarea>`),field('Type',`<select name="type">${['SOP','FAQ','Reference','Macro'].map(v=>`<option ${item?.type===v?'selected':''}>${v}</option>`).join('')}</select>`),field('Content',`<textarea name="content" class="editor-content">${esc(item?.content||'')}</textarea>`),`<div class="form-grid">${field('Owner',`<input name="owner" value="${esc(item?.owner||state.data.me?.name||'')}">`)}${field('Review date',`<input type="date" name="reviewDate" value="${esc((item?.reviewDate||'').slice(0,10))}">`)}</div>`,`<fieldset><legend>Target Call Center groups</legend>${groupChecks(arr(item?.targetGroupIds))}</fieldset>`,field('Attachments',`<input type="file" name="attachments" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.docx,.pptx,.xlsx,.mp4">`)].join('');
  if(collection==='decisions')html=[field('Decision',`<textarea name="decision" required>${esc(item?.decision||'')}</textarea>`),field('Reason',`<textarea name="reason" class="tall">${esc(item?.reason||'')}</textarea>`),field('Impact',`<textarea name="impact" class="tall">${esc(item?.impact||'')}</textarea>`),`<div class="form-grid">${field('Owner',`<input name="owner" value="${esc(item?.owner||state.data.me?.name||'')}">`)}${field('Review date',`<input type="date" name="reviewDate" value="${esc((item?.reviewDate||'').slice(0,10))}">`)}</div>`].join('');
  $('#editorFields').innerHTML=html;const draftKey=`hub-draft:${collection}:${item?.id||'new'}`;if(!item){const saved=localStorage.getItem(draftKey);if(saved){try{const draft=JSON.parse(saved);for(const [k,v] of Object.entries(draft)){const input=$(`[name="${CSS.escape(k)}"]`,$('#editorForm'));if(input&&input.type!=='file'){if(input.type==='checkbox')input.checked=Boolean(v);else input.value=v;}}$('#draftNotice').classList.remove('hidden');}catch{}}else $('#draftNotice').classList.add('hidden');}else $('#draftNotice').classList.add('hidden');state.editor.draftKey=draftKey;$('#editorModal').showModal();}
function serializeForm(form){const fd=new FormData(form),out={};for(const [key,val] of fd){if(val instanceof File)continue;if(key in out)out[key]=arr(out[key]).length?[...arr(out[key]),val]:[out[key],val];else out[key]=val;}for(const box of $$('input[type=checkbox]',form)){if(!box.name)continue;if(box.name==='targetGroupIds')continue;out[box.name]=box.checked;}out.targetGroupIds=$$('input[name=targetGroupIds]:checked',form).map(x=>x.value);return out;}
async function saveEditor(event){event.preventDefault();const form=event.currentTarget,{collection,id}=state.editor;try{setLoading(true,'Saving…');const item={...serializeForm(form),id};item.attachmentIds=id?arr(find(collection,id)?.attachmentIds):[];const files=$('input[name=attachments]',form)?.files||[];for(const file of files){const out=await api('files/upload',{method:'POST',body:{title:file.name,fileName:file.name,dataBase64:await fileToBase64(file)}});item.attachmentIds.push(out.attachment.id);upsert('attachments',out.attachment);}const out=await api('item',{method:id?'PUT':'POST',body:{collection,item}});upsert(collection,out.item);localStorage.removeItem(state.editor.draftKey);state.dirty=false;$('#editorModal').close();toast(id?'Updated.':'Created.','success');renderAll();}catch(e){toast(e.message,'error');}finally{setLoading(false);}}
function safeCloseEditor(){if(state.dirty&&!confirm('Discard unsaved changes?'))return;state.dirty=false;$('#editorModal').close();}

// ---------- Course + quiz ----------
function openCourse(id){const course=find('courses',id);if(!course)return;const progress=state.data.progress||{};$('#courseModalBody').innerHTML=`<span class="eyebrow">LEARNING</span><h2>${esc(course.title)}</h2><p class="lead">${esc(course.description||'')}</p><div class="course-meta">${course.required?pill('Required','pending'):pill('Optional')} ${course.dueDate?pill(`Due ${fmt(course.dueDate)}`,isPast(course.dueDate)&&!course.progress?.completed?'critical':''):''}</div><div class="module-list">${arr(course.modules).map((m,i)=>{const done=progress.modules?.[`${course.id}:${m.id}`]?.completed;return `<article class="module-card ${done?'done':''}"><div><span class="module-number">${i+1}</span><strong>${esc(m.title)}</strong><small>${esc(m.type)}</small></div><div class="row-actions">${done?pill('Complete','approved'):''}${m.type==='resource'?`<button class="btn primary compact" data-open-resource="${m.resourceId}" data-course-id="${course.id}" data-module-id="${m.id}">Open</button>${done?'':`<button class="small-btn" data-complete-module="${course.id}" data-module="${m.id}">Mark complete</button>`}`:m.type==='quiz'?`<button class="btn primary compact" data-start-quiz="${m.quizId}" data-course-id="${course.id}" data-module-id="${m.id}">Take quiz</button>`:m.type==='link'?`<a class="btn primary compact" target="_blank" rel="noopener" href="${esc(m.link)}">Open link</a><button class="small-btn" data-complete-module="${course.id}" data-module="${m.id}">Mark complete</button>`:`<button class="btn ghost compact" data-text-module="${course.id}" data-module="${m.id}">Read</button>`}</div>${m.type==='text'?`<div class="module-text hidden" data-module-text="${m.id}">${nl2br(m.text||'')}</div>`:''}</article>`;}).join('')||empty('This course does not have modules yet.')}</div>`;$('#courseModal').showModal();}
async function startQuiz(id){try{const out=await api('learning/quiz-start',{method:'POST',body:{quizId:id}});const q=out.quiz;$('#courseModalBody').innerHTML=`<span class="eyebrow">QUIZ</span><h2>${esc(q.title)}</h2><p>${esc(q.description||'')}</p><form id="quizForm" data-session="${out.sessionId}" class="quiz-form">${q.questions.map((question,i)=>`<fieldset class="quiz-question"><legend>${i+1}. ${esc(question.prompt)}</legend>${question.options.map((opt,j)=>`<label><input type="${question.type==='multiple'?'checkbox':'radio'}" name="q_${question.id}" value="${j}"> ${esc(opt)}</label>`).join('')}</fieldset>`).join('')}<button class="btn primary" type="submit">Submit quiz</button></form>`;}catch(e){toast(e.message,'error');}}
async function submitQuiz(event){event.preventDefault();const form=event.currentTarget;const answers={};$$('fieldset',form).forEach(fs=>{const inputs=$$('input:checked',fs);if(inputs.length){const id=inputs[0].name.replace(/^q_/,'');answers[id]=inputs.map(x=>Number(x.value));}});try{const out=await api('learning/quiz-submit',{method:'POST',body:{sessionId:form.dataset.session,answers}});state.data.progress=out.progress;$('#courseModalBody').innerHTML=`<div class="quiz-result ${out.passed?'passed':'failed'}"><span class="eyebrow">RESULT</span><h2>${out.score}%</h2><strong>${out.passed?'Passed':'Not passed yet'}</strong><p>${out.passed?'Nice work. Your progress has been updated.':'Review the material and try again if attempts remain.'}</p><div class="stack">${arr(out.results).filter(r=>r.explanation).map((r,i)=>`<div class="history-item"><strong>Question ${i+1}: ${r.correct?'Correct':'Review'}</strong><span>${esc(r.explanation)}</span></div>`).join('')}</div><button class="btn primary" data-close-course>Done</button></div>`;await refresh('courses,progress,notifications',{quiet:true});}catch(e){toast(e.message,'error');}}

// ---------- Admin modals ----------
function openSimpleAdmin(title,bodyHtml,kind,id=''){$('#adminModalBody').innerHTML=`<span class="eyebrow">ADMIN</span><h2>${esc(title)}</h2><form id="adminActionForm" data-kind="${kind}" data-id="${esc(id)}" class="form-stack">${bodyHtml}<button class="btn primary" type="submit">Save</button></form>`;$('#adminModal').showModal();}
function openResourceUpload(existing=null,replace=false){if(existing?.sourceType==='google-drive')return openDriveResource(existing);const title=replace?'Replace file':existing?'Edit resource':'Upload content';const file=replace||!existing?field('File',`<input type="file" name="file" required accept=".pdf,.png,.jpg,.jpeg,.gif,.webp,.txt,.csv,.docx,.pptx,.xlsx,.mp4">`):'';openSimpleAdmin(title,`${field('Title',`<input name="title" value="${esc(existing?.title||'')}">`)}${field('Description',`<textarea name="description">${esc(existing?.description||'')}</textarea>`)}${field('Category',`<input name="category" value="${esc(existing?.category||'General')}">`)}${field('Review date',`<input type="date" name="reviewDate" value="${esc((existing?.reviewDate||'').slice(0,10))}">`)}${file}`,replace?'resource-replace':existing?'resource-edit':'resource-upload',existing?.id||'');}
function openDriveResource(existing=null){openSimpleAdmin(existing?'Edit Google Drive resource':'Add from Google Drive',`${field('Google Drive link',`<input type="url" name="externalUrl" required placeholder="https://drive.google.com/..." value="${esc(existing?.externalUrl||'')}">`)}<p class="muted">Use a Google Drive or Google Docs/Sheets/Slides sharing link. Make sure the intended learners have permission to open it.</p>${field('Title',`<input name="title" required value="${esc(existing?.title||'')}">`)}${field('Description',`<textarea name="description">${esc(existing?.description||'')}</textarea>`)}${field('Category',`<input name="category" value="${esc(existing?.category||'General')}">`)}${field('Review date',`<input type="date" name="reviewDate" value="${esc((existing?.reviewDate||'').slice(0,10))}">`)}`,'resource-drive',existing?.id||'');}
function openGroup(group=null){openSimpleAdmin(group?'Edit group':'New Call Center group',`${field('Name',`<input name="name" required value="${esc(group?.name||'')}">`)}${field('Description',`<textarea name="description">${esc(group?.description||'')}</textarea>`)}`,group?'group-edit':'group-new',group?.id||'');}
function openUserGroups(user){const groups=arr(state.data.groups);openSimpleAdmin(`Groups for ${user.name}`,`<div class="groups-check">${groups.map(g=>`<label><input type="checkbox" name="groupIds" value="${g.id}" ${arr(user.groupIds).includes(g.id)?'checked':''}> ${esc(g.name)}</label>`).join('')}</div>`,'user-groups',user.id);}
function openQuestion(){openSimpleAdmin('New question',`${field('Type',`<select name="type"><option value="single">Multiple choice (one)</option><option value="multiple">Multiple select</option><option value="truefalse">True/False</option></select>`)}${field('Question',`<textarea name="prompt" required></textarea>`)}${field('Options (one per line)',`<textarea name="options" placeholder="Option 1\nOption 2"></textarea>`)}${field('Correct option numbers (comma separated, starting at 1)',`<input name="correct" placeholder="1">`)}${field('Explanation',`<textarea name="explanation"></textarea>`)}`,'question-new');}
function openQuiz(){const questions=arr(state.data.questionBank);openSimpleAdmin('Create quiz',`${field('Title',`<input name="title" required>`)}${field('Description',`<textarea name="description"></textarea>`)}<fieldset><legend>Questions</legend><div class="groups-check">${questions.map(q=>`<label><input type="checkbox" name="questionIds" value="${q.id}"> ${esc(q.prompt)}</label>`).join('')||'<p class="muted">Create questions first.</p>'}</div></fieldset><div class="form-grid">${field('Pass mark %',`<input name="passMark" type="number" value="80" min="0" max="100">`)}${field('Max attempts',`<input name="maxAttempts" type="number" value="3" min="1" max="20">`)}</div><label><input type="checkbox" name="shuffle" checked> Randomize questions</label>`,'quiz-new');}
function openCourseAdmin(course=null){const resources=arr(state.data.resources).filter(r=>r.status!=='Archived'),quizzes=arr(state.data.quizzes),groups=arr(state.data.groups),users=state.adminUsers;const modules=arr(course?.modules);const modHtml=modules.map((m,i)=>moduleBuilder(m,i,resources,quizzes)).join('');$('#adminModalBody').innerHTML=`<span class="eyebrow">LEARNING ADMIN</span><h2>${course?'Edit':'Create'} course</h2><form id="courseAdminForm" data-id="${course?.id||''}" class="form-stack">${field('Title',`<input name="title" required value="${esc(course?.title||'')}">`)}${field('Description',`<textarea name="description">${esc(course?.description||'')}</textarea>`)}<div class="form-grid">${field('Status',`<select name="status">${['Draft','Active','Archived'].map(v=>`<option ${course?.status===v?'selected':''}>${v}</option>`).join('')}</select>`)}${field('Due date',`<input name="dueDate" type="date" value="${esc((course?.dueDate||'').slice(0,10))}">`)}</div><label><input type="checkbox" name="required" ${course?.required?'checked':''}> Required learning</label><fieldset><legend>Assign to Call Center groups</legend><input type="search" data-group-search placeholder="Search groups"><div class="groups-check">${groups.map(g=>`<label><input type="checkbox" name="assignedGroupIds" value="${g.id}" ${arr(course?.assignedGroupIds).includes(g.id)?'checked':''}> ${esc(g.name)}</label>`).join('')||'<span class="muted">No groups: leave blank to assign to everyone.</span>'}</div></fieldset><fieldset><legend>Assign to specific users (optional)</legend><div class="groups-check scroll-box">${users.map(u=>`<label><input type="checkbox" name="assignedUserIds" value="${u.id}" ${arr(course?.assignedUserIds).includes(u.id)?'checked':''}> ${esc(u.name)}</label>`).join('')}</div></fieldset><section><div class="section-heading"><h3>Modules</h3><div class="tool-actions"><button type="button" class="small-btn" data-add-module="resource">+ Document</button><button type="button" class="small-btn" data-add-module="quiz">+ Quiz</button><button type="button" class="small-btn" data-add-module="text">+ Text</button><button type="button" class="small-btn" data-add-module="link">+ Link</button></div></div><div id="moduleBuilder">${modHtml}</div></section><button class="btn primary" type="submit">Save course</button></form>`;$('#adminModal').showModal();}
function moduleBuilder(m={type:'resource',title:'New module'},i=0,resources=arr(state.data.resources).filter(r=>r.status!=='Archived'),quizzes=arr(state.data.quizzes)){const type=m.type||'resource';let content='';if(type==='resource')content=`<select name="moduleResource"><option value="">Select document</option>${resources.map(r=>`<option value="${r.id}" ${m.resourceId===r.id?'selected':''}>${esc(r.title)}</option>`).join('')}</select><label class="inline-upload-btn">Upload new document<input type="file" data-inline-resource hidden accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.docx,.pptx,.xlsx,.mp4"></label>`;if(type==='quiz')content=`<select name="moduleQuiz"><option value="">Select quiz</option>${quizzes.map(q=>`<option value="${q.id}" ${m.quizId===q.id?'selected':''}>${esc(q.title)}</option>`).join('')}</select>`;if(type==='text')content=`<textarea name="moduleText">${esc(m.text||'')}</textarea>`;if(type==='link')content=`<input name="moduleLink" type="url" value="${esc(m.link||'')}">`;return `<article class="module-builder-card" data-module-card data-type="${type}" data-id="${esc(m.id||'')}"><div class="section-heading"><strong>${i+1}. ${esc(m.title||'New module')}</strong><div class="row-actions"><button type="button" class="small-btn" data-module-up>↑</button><button type="button" class="small-btn" data-module-down>↓</button><button type="button" class="small-btn danger-outline" data-module-remove>Remove</button></div></div><input name="moduleTitle" value="${esc(m.title||'New module')}" aria-label="Module title"><div class="module-resource-picker">${content}</div><label><input type="checkbox" name="moduleRequired" ${m.required===false?'':'checked'}> Required module</label></article>`;}

async function submitAdminAction(event){event.preventDefault();const form=event.currentTarget,kind=form.dataset.kind,id=form.dataset.id,fd=new FormData(form);try{setLoading(true,'Saving…');
  if(kind.startsWith('resource-')){if(kind==='resource-drive'){const out=await api('learning/resource-link',{method:'POST',body:{id:id||undefined,externalUrl:fd.get('externalUrl'),title:fd.get('title'),description:fd.get('description'),category:fd.get('category'),reviewDate:fd.get('reviewDate')}});upsert('resources',out.resource);}else if(kind==='resource-edit'){const out=await api('learning/resource-manage',{method:'POST',body:{action:'update',id,title:fd.get('title'),description:fd.get('description'),category:fd.get('category'),reviewDate:fd.get('reviewDate')}});upsert('resources',out.resource);}else{const file=fd.get('file');if(!(file instanceof File)||!file.size)throw new Error('Choose a file.');const out=await api('learning/resource-upload',{method:'POST',body:{id:kind==='resource-replace'?id:undefined,title:fd.get('title')||file.name,description:fd.get('description'),category:fd.get('category'),reviewDate:fd.get('reviewDate'),fileName:file.name,dataBase64:await fileToBase64(file)}});upsert('resources',out.resource);}}
  if(kind==='group-new'||kind==='group-edit'){const out=await api('admin/group',{method:'POST',body:{action:kind==='group-new'?'create':'update',id,name:fd.get('name'),description:fd.get('description')}});upsert('groups',out.group);}
  if(kind==='user-groups'){const groupIds=fd.getAll('groupIds');const out=await api('admin/user',{method:'POST',body:{action:'groups',userId:id,groupIds}});const i=state.adminUsers.findIndex(u=>u.id===id);if(i>=0)state.adminUsers[i]=out.user;}
  if(kind==='question-new'){let options=String(fd.get('options')||'').split(/\n/).map(x=>x.trim()).filter(Boolean);if(fd.get('type')==='truefalse')options=['True','False'];const correct=String(fd.get('correct')||'1').split(',').map(x=>Number(x.trim())-1).filter(x=>x>=0);const out=await api('learning/question',{method:'POST',body:{type:fd.get('type'),prompt:fd.get('prompt'),options,correct,explanation:fd.get('explanation')}});state.data.questionBank=out.questionBank;}
  if(kind==='quiz-new'){const out=await api('learning/quiz',{method:'POST',body:{title:fd.get('title'),description:fd.get('description'),questionIds:fd.getAll('questionIds'),passMark:Number(fd.get('passMark')),maxAttempts:Number(fd.get('maxAttempts')),shuffle:fd.has('shuffle')}});upsert('quizzes',out.quiz);}
  $('#adminModal').close();toast('Saved.','success');renderAll();
 }catch(e){toast(e.message,'error');}finally{setLoading(false);}}
async function submitCourseAdmin(event){event.preventDefault();const form=event.currentTarget,fd=new FormData(form);try{setLoading(true,'Saving course…');const modules=[];for(const card of $$('[data-module-card]',form)){const type=card.dataset.type;const m={id:card.dataset.id||undefined,title:$('[name=moduleTitle]',card).value,type,required:$('[name=moduleRequired]',card).checked};if(type==='resource')m.resourceId=$('[name=moduleResource]',card).value;if(type==='quiz')m.quizId=$('[name=moduleQuiz]',card).value;if(type==='text')m.text=$('[name=moduleText]',card).value;if(type==='link')m.link=$('[name=moduleLink]',card).value;modules.push(m);}const out=await api('learning/course',{method:'POST',body:{id:form.dataset.id||undefined,title:fd.get('title'),description:fd.get('description'),status:fd.get('status'),dueDate:fd.get('dueDate'),required:fd.has('required'),assignedGroupIds:fd.getAll('assignedGroupIds'),assignedUserIds:fd.getAll('assignedUserIds'),modules}});upsert('courses',out.course);$('#adminModal').close();toast('Course saved.','success');renderAll();}catch(e){toast(e.message,'error');}finally{setLoading(false);}}

function openOpsEditor(collection,item=null){if(collection==='roster'&&!isAdmin())return;let title,body;if(collection==='incidents'){title=item?'Edit incident':'New incident';body=`${field('Title',`<input name="title" required value="${esc(item?.title||'')}">`)}<div class="form-grid">${field('Severity',`<select name="severity">${['Critical','High','Medium','Low'].map(v=>`<option ${item?.severity===v?'selected':''}>${v}</option>`).join('')}</select>`)}${field('Status',`<select name="status">${['Open','Investigating','Monitoring','Resolved','Archived'].map(v=>`<option ${item?.status===v?'selected':''}>${v}</option>`).join('')}</select>`)}</div>${field('Summary',`<textarea name="summary">${esc(item?.summary||'')}</textarea>`)}${field('Details',`<textarea name="details" class="tall">${esc(item?.details||'')}</textarea>`)}${field('Owner',`<input name="owner" value="${esc(item?.owner||state.data.me?.name||'')}">`)}${field('Next action',`<input name="nextAction" value="${esc(item?.nextAction||'')}">`)}${field('Due',`<input type="datetime-local" name="dueAt" value="${esc((item?.dueAt||'').slice(0,16))}">`)}`;}
  if(collection==='handoffs'){title=item?'Edit handoff':'New shift handoff';body=`${field('Shift date',`<input type="date" name="shiftDate" value="${esc((item?.shiftDate||new Date().toISOString()).slice(0,10))}">`)}${field('Shift name',`<input name="shiftName" value="${esc(item?.shiftName||'')}">`)}<div class="form-grid">${field('Outgoing',`<input name="outgoing" value="${esc(item?.outgoing||'')}">`)}${field('Incoming',`<input name="incoming" value="${esc(item?.incoming||'')}">`)}</div>${field('Summary',`<textarea name="summary">${esc(item?.summary||'')}</textarea>`)}${field('Outstanding',`<textarea name="outstanding">${esc(item?.outstanding||'')}</textarea>`)}${field('Priorities for next shift',`<textarea name="priorities">${esc(item?.priorities||'')}</textarea>`)}`;}
  if(collection==='roster'){title=item?'Edit roster entry':'New roster entry';body=`${field('Name',`<input name="name" required value="${esc(item?.name||'')}">`)}${field('Role / coverage',`<input name="role" value="${esc(item?.role||'On call')}">`)}<div class="form-grid">${field('Starts',`<input type="datetime-local" name="startAt" value="${esc((item?.startAt||'').slice(0,16))}">`)}${field('Ends',`<input type="datetime-local" name="endAt" value="${esc((item?.endAt||'').slice(0,16))}">`)}</div>${field('Notes',`<textarea name="notes">${esc(item?.notes||'')}</textarea>`)}`;}
  $('#opsModalBody').innerHTML=`<span class="eyebrow">OPERATIONS</span><h2>${esc(title)}</h2><form id="opsForm" data-collection="${collection}" data-id="${item?.id||''}" class="form-stack">${body}<button class="btn primary">Save</button></form>`;$('#opsModal').showModal();}
async function saveOps(event){event.preventDefault();const form=event.currentTarget,collection=form.dataset.collection,fd=new FormData(form),body=Object.fromEntries(fd);if(form.dataset.id)body.id=form.dataset.id;try{const out=await api(`operations/${collection==='incidents'?'incident':collection==='handoffs'?'handoff':'roster'}`,{method:form.dataset.id?'PUT':'POST',body});upsert(collection,out.item);$('#opsModal').close();toast('Saved.','success');renderAll();}catch(e){toast(e.message,'error');}}

// ---------- Security / MFA ----------
function openSecurity(){const me=state.data.me;$('#securityModalBody').innerHTML=me.mfaEnabled?`<span class="eyebrow">ACCOUNT SECURITY</span><h2>Two-factor authentication</h2><p>MFA is enabled for your account.</p><form id="disableMfaForm" class="form-stack">${field('Password',`<input type="password" name="password" required>`)}${field('Authenticator code',`<input name="code" inputmode="numeric" maxlength="6" required>`)}<button class="btn danger">Disable MFA</button></form>`:`<span class="eyebrow">ACCOUNT SECURITY</span><h2>Add two-factor authentication</h2><p>Use an authenticator app for a second sign-in factor.</p><button class="btn primary" id="setupMfa">Set up MFA</button><div id="mfaSetupArea"></div>`;$('#securityModal').showModal();}

// ---------- Handlers ----------
async function markNotification(button){const id=button.dataset.notification,view=button.dataset.view,item=button.dataset.item;try{const out=await api('notifications/read',{method:'POST',body:{id}});state.data.notifications=out.notifications||[];renderNotifications();renderHome();}catch{}setView(view||'home');if(item){const collection=view==='communications'?'updates':view==='knowledge'?'docs':view==='operations'?(find('incidents',item)?'incidents':find('handoffs',item)?'handoffs':'roster'):null;if(collection)openItem(collection,item);if(view==='learning')openCourse(item);}}
function highlight(text,q){const terms=String(q||'').trim().split(/\s+/).filter(Boolean).sort((a,b)=>b.length-a.length);if(!terms.length)return esc(text);const pattern=new RegExp(`(${terms.map(t=>t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')})`,'ig');return String(text||'').split(pattern).map((part,i)=>i%2?`<mark>${esc(part)}</mark>`:esc(part)).join('');}
async function doSearch(q){state.searchQuery=q;if(q.trim().length<2){state.searchResults=[];return;}try{const out=await searchWorkspace(q.trim());state.searchResults=out.results||[];renderSearch();setView('search');}catch(e){if(e.code!=='NETWORK')toast(e.message,'error');}}
let searchTimer;

// ---------- Event delegation ----------
document.addEventListener('click',async event=>{
  const nav=event.target.closest('[data-view]');if(nav&&nav.classList.contains('nav-item'))return setView(nav.dataset.view);
  const jump=event.target.closest('[data-jump]');if(jump)return setView(jump.dataset.jump);
  const open=event.target.closest('[data-open]');if(open)return openItem(open.dataset.open,open.dataset.id);
  const course=event.target.closest('[data-course]');if(course)return openCourse(course.dataset.course);
  const filter=event.target.closest('[data-comm-filter]');if(filter){state.commFilter=filter.dataset.commFilter;$$('#commFilters .chip').forEach(b=>b.classList.toggle('active',b===filter));return renderCommunications();}
  const df=event.target.closest('[data-doc-filter]');if(df){state.docFilter=df.dataset.docFilter;$$('#knowledgeFilters .chip').forEach(b=>b.classList.toggle('active',b===df));return renderKnowledge();}
  const cf=event.target.closest('[data-course-filter]');if(cf){state.courseFilter=cf.dataset.courseFilter;$$('#learningFilters .chip').forEach(b=>b.classList.toggle('active',b===cf));return renderLearning();}
  const decf=event.target.closest('[data-decision-filter]');if(decf){state.decisionFilter=decf.dataset.decisionFilter;$$('#decisionFilters .chip').forEach(b=>b.classList.toggle('active',b===decf));return renderDecisions();}
  const ot=event.target.closest('[data-ops-tab]');if(ot){state.opsTab=ot.dataset.opsTab;return renderOperations();}
  const at=event.target.closest('[data-admin-tab]');if(at){state.adminTab=at.dataset.adminTab;if(at.dataset.adminTab==='users'&&!state.adminUsers.length)await loadAdminUsers();if(at.dataset.adminTab==='learning'&&!state.adminUsers.length)await loadAdminUsers();return renderAdmin();}
  const create=event.target.closest('[data-create]');if(create)return openEditor(create.dataset.create);
  const edit=event.target.closest('[data-edit]');if(edit){$('#itemModal').close();return openEditor(edit.dataset.edit,find(edit.dataset.edit,edit.dataset.id));}
  const closeEditor=event.target.closest('[data-close-editor]');if(closeEditor)return safeCloseEditor();
  if(event.target.closest('[data-close-item]'))return $('#itemModal').close();if(event.target.closest('[data-close-course]'))return $('#courseModal').close();if(event.target.closest('[data-close-admin-modal]'))return $('#adminModal').close();if(event.target.closest('[data-close-ops-modal]'))return $('#opsModal').close();if(event.target.closest('[data-close-security]'))return $('#securityModal').close();
  if(event.target.closest('#notificationButton'))return $('#notificationPanel').classList.toggle('hidden');if(event.target.closest('[data-close-panel]'))return $('#notificationPanel').classList.add('hidden');if(event.target.closest('#profileButton'))return $('#profilePanel').classList.toggle('hidden');if(event.target.closest('[data-close-profile]'))return $('#profilePanel').classList.add('hidden');
  const note=event.target.closest('[data-notification]');if(note)return markNotification(note);
  if(event.target.closest('[data-clear-notifications]')){try{const out=await api('notifications/read',{method:'POST',body:{all:true}});state.data.notifications=out.notifications||[];renderAll();}catch(e){toast(e.message,'error');}return;}
  const ack=event.target.closest('[data-ack]');if(ack){try{const out=await api('ack',{method:'POST',body:{updateId:ack.dataset.ack}});upsert('updates',out.item);$('#itemModal').close();toast('Acknowledged.','success');await refresh('notifications',{quiet:true});}catch(e){toast(e.message,'error');}return;}
  const ar=event.target.closest('[data-archive]');if(ar){const item=find(ar.dataset.archive,ar.dataset.id);try{if(item?.status==='Archived'){await api('content/bulk',{method:'POST',body:{collection:ar.dataset.archive,ids:[ar.dataset.id],action:'restore'}});item.status='Active';item.updatedAt=new Date().toISOString();}else{const out=await api('item',{method:'DELETE',body:{collection:ar.dataset.archive,id:ar.dataset.id}});upsert(ar.dataset.archive,out.item);}$('#itemModal').close();renderAll();toast('Updated.','success');}catch(e){toast(e.message,'error');}return;}
  const del=event.target.closest('[data-permanent-delete]');if(del&&confirm('Permanently delete this communication and its acknowledgement record? This cannot be undone.')){try{await api('item/permanent',{method:'DELETE',body:{collection:'updates',id:del.dataset.permanentDelete}});remove('updates',del.dataset.permanentDelete);$('#itemModal').close();renderAll();toast('Communication permanently deleted.','success');}catch(e){toast(e.message,'error');}return;}
  const macro=event.target.closest('[data-copy-macro]');if(macro){const doc=find('docs',macro.dataset.copyMacro);return copyText(doc?.content||'');}
  const resolve=event.target.closest('[data-resolve-feedback]');if(resolve){try{const out=await api('knowledge/comment',{method:'POST',body:{action:'resolve',docId:resolve.dataset.doc,entryId:resolve.dataset.resolveFeedback}});upsert('docs',out.item);openItem('docs',out.item.id);}catch(e){toast(e.message,'error');}return;}
  const searchOpen=event.target.closest('[data-search-open]');if(searchOpen){setView(searchOpen.dataset.searchOpen);const v=searchOpen.dataset.searchOpen;if(v==='learning')openCourse(searchOpen.dataset.id);else if(v==='communications')openItem('updates',searchOpen.dataset.id);else if(v==='knowledge')openItem('docs',searchOpen.dataset.id);else if(v==='decisions')openItem('decisions',searchOpen.dataset.id);else if(v==='operations'){const id=searchOpen.dataset.id;openItem(find('incidents',id)?'incidents':'handoffs',id);}return;}
  if(event.target.closest('#themeToggle'))return applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
  if(event.target.closest('#calendarExport')){const events=[];for(const c of arr(state.data.courses))if(c.dueDate&&!c.progress?.completed)events.push({id:`course-${c.id}`,date:c.dueDate,title:`Learning due: ${c.title}`});for(const d of [...arr(state.data.docs),...arr(state.data.updates),...arr(state.data.decisions)])if(d.reviewDate)events.push({id:`review-${d.id}`,date:d.reviewDate,title:`Review: ${d.title||d.decision}`});for(const r of arr(state.data.roster))if(r.startAt)events.push({id:`roster-${r.id}`,date:r.startAt,title:`Roster: ${r.name}`});downloadIcs('call-center-hub-dates.ics',events);return;}
  if(event.target.closest('#retryButton'))return bootstrap();
  if(event.target.closest('#logoutButton')){try{await api('auth/logout',{method:'POST',body:{}});}catch{}state.data={};showAuth('login');return;}
  if(event.target.closest('#mfaButton'))return openSecurity();
  if(event.target.closest('#setupMfa')){try{const out=await api('auth/mfa/setup',{method:'POST',body:{}});$('#mfaSetupArea').innerHTML=`<div class="section-card"><p>Add this key manually in your authenticator app:</p><code class="secret-code">${esc(out.secret)}</code><form id="enableMfaForm" class="form-stack"><input type="hidden" name="challenge" value="${esc(out.challenge)}">${field('6-digit code',`<input name="code" inputmode="numeric" maxlength="6" required>`)}<button class="btn primary">Enable MFA</button></form></div>`;}catch(e){toast(e.message,'error');}return;}
  if(event.target.closest('#opsCreateButton'))return openOpsEditor(state.opsTab);
  const eops=event.target.closest('[data-edit-ops]');if(eops){$('#itemModal').close();return openOpsEditor(eops.dataset.editOps,find(eops.dataset.editOps,eops.dataset.id));}
  const aops=event.target.closest('[data-archive-ops]');if(aops&&confirm('Archive this operations record?')){const path=aops.dataset.archiveOps==='incidents'?'incident':aops.dataset.archiveOps==='handoffs'?'handoff':'roster';try{const out=await api(`operations/${path}`,{method:'DELETE',body:{id:aops.dataset.id}});upsert(aops.dataset.archiveOps,out.item);$('#itemModal').close();renderAll();}catch(e){toast(e.message,'error');}return;}
  const ropen=event.target.closest('[data-open-resource]');if(ropen){try{const out=await api('learning/resource-open',{method:'POST',body:{resourceId:ropen.dataset.openResource}});window.open(out.url,'_blank','noopener');toast('Document opened.','success');}catch(e){toast(e.message,'error');}return;}
  const resOpen=event.target.closest('[data-resource-open]');if(resOpen){try{const out=await api('learning/resource-open',{method:'POST',body:{resourceId:resOpen.dataset.resourceOpen}});window.open(out.url,'_blank','noopener');}catch(e){toast(e.message,'error');}return;}
  const complete=event.target.closest('[data-complete-module]');if(complete){try{const out=await api('learning/module-complete',{method:'POST',body:{courseId:complete.dataset.completeModule,moduleId:complete.dataset.module}});state.data.progress=out.progress;await refresh('courses,notifications',{quiet:true});openCourse(complete.dataset.completeModule);}catch(e){toast(e.message,'error');}return;}
  const textModule=event.target.closest('[data-text-module]');if(textModule){const box=$(`[data-module-text="${CSS.escape(textModule.dataset.module)}"]`);box?.classList.toggle('hidden');if(box&&!box.classList.contains('hidden')){try{const out=await api('learning/module-complete',{method:'POST',body:{courseId:textModule.dataset.textModule,moduleId:textModule.dataset.module}});state.data.progress=out.progress;await refresh('courses',{quiet:true});}catch{}}return;}
  const sq=event.target.closest('[data-start-quiz]');if(sq)return startQuiz(sq.dataset.startQuiz);
  const adminTabButton=event.target.closest('[data-load-reports]');if(adminTabButton){try{setLoading(true,'Loading reports…');state.analytics=await api('admin/analytics');renderReports();}catch(e){toast(e.message,'error');}finally{setLoading(false);}return;}
  const exportBtn=event.target.closest('[data-export-report]');if(exportBtn&&state.analytics)return downloadCsv(`hub-${exportBtn.dataset.exportReport}.csv`,arr(state.analytics[exportBtn.dataset.exportReport]));
  if(event.target.closest('[data-new-group]'))return openGroup();const eg=event.target.closest('[data-edit-group]');if(eg)return openGroup(find('groups',eg.dataset.editGroup));const dg=event.target.closest('[data-delete-group]');if(dg&&confirm('Delete this Call Center group? Users will be unassigned from it.')){try{await api('admin/group',{method:'POST',body:{action:'delete',id:dg.dataset.deleteGroup}});remove('groups',dg.dataset.deleteGroup);renderAll();}catch(e){toast(e.message,'error');}return;}
  const userGroups=event.target.closest('[data-user-groups]');if(userGroups)return openUserGroups(state.adminUsers.find(u=>u.id===userGroups.dataset.userGroups));const userReset=event.target.closest('[data-user-reset]');if(userReset){const password=prompt('Enter a temporary password (10+ characters with a letter and number). The user should change it through Forgot password when email delivery is configured.','');if(!password)return;try{await api('admin/user',{method:'POST',body:{action:'reset-password',userId:userReset.dataset.userReset,password}});toast('Temporary password set and existing sessions revoked.','success');}catch(e){toast(e.message,'error');}return;}const userStatus=event.target.closest('[data-user-status]');if(userStatus){const u=state.adminUsers.find(x=>x.id===userStatus.dataset.userStatus);try{const out=await api('admin/user',{method:'POST',body:{action:'status',userId:u.id,status:u.status==='active'?'suspended':'active'}});Object.assign(u,out.user);renderAdminUsers();}catch(e){toast(e.message,'error');}return;}
  const approval=event.target.closest('[data-approve]');if(approval){try{const out=await api('approve',{method:'POST',body:{collection:approval.dataset.collection,id:approval.dataset.id,decision:approval.dataset.approve}});upsert(approval.dataset.collection,out.item);renderAll();toast(`Content ${approval.dataset.approve}.`,'success');}catch(e){toast(e.message,'error');}return;}
  if(event.target.closest('[data-resource-upload]'))return openResourceUpload();if(event.target.closest('[data-resource-drive]'))return openDriveResource();const redit=event.target.closest('[data-resource-edit]');if(redit)return openResourceUpload(find('resources',redit.dataset.resourceEdit));const rrep=event.target.closest('[data-resource-replace]');if(rrep)return openResourceUpload(find('resources',rrep.dataset.resourceReplace),true);const ract=event.target.closest('[data-resource-action]');if(ract){if(ract.dataset.resourceAction==='delete'&&!confirm('Permanently delete this unused learning resource?'))return;try{const out=await api('learning/resource-manage',{method:'POST',body:{action:ract.dataset.resourceAction,id:ract.dataset.id}});if(out.deleted)remove('resources',ract.dataset.id);else if(out.resource)upsert('resources',out.resource);renderAll();toast('Resource updated.','success');}catch(e){toast(e.message,'error');}return;}
  if(event.target.closest('[data-question-admin]'))return openQuestion();if(event.target.closest('[data-quiz-admin]'))return openQuiz();const ca=event.target.closest('[data-course-admin]');if(ca)return openCourseAdmin(ca.dataset.courseAdmin?find('courses',ca.dataset.courseAdmin):null);
  const addm=event.target.closest('[data-add-module]');if(addm){const builder=$('#moduleBuilder');builder.insertAdjacentHTML('beforeend',moduleBuilder({type:addm.dataset.addModule,title:'New module'},$$('[data-module-card]',builder).length));return;}
  const rm=event.target.closest('[data-module-remove]');if(rm)return rm.closest('[data-module-card]').remove();const up=event.target.closest('[data-module-up]');if(up){const card=up.closest('[data-module-card]');card.previousElementSibling?.before(card);return;}const down=event.target.closest('[data-module-down]');if(down){const card=down.closest('[data-module-card]');card.nextElementSibling?.after(card);return;}
  const bulkRole=event.target.closest('[data-bulk-user="role"]');if(bulkRole){const role=prompt('Set selected users to role: viewer, editor, or admin','viewer');if(!['viewer','editor','admin'].includes(role))return;try{await api('admin/users/bulk',{method:'POST',body:{action:'role',userIds:[...state.adminUsersSelected],role}});await loadAdminUsers();renderAdminUsers();}catch(e){toast(e.message,'error');}return;}
  const bulkGroups=event.target.closest('[data-bulk-user="groups"]');if(bulkGroups){const names=arr(state.data.groups).map(g=>g.name).join(', ');const answer=prompt(`Enter group names separated by commas. Available: ${names}`,'');if(answer===null)return;const wanted=answer.split(',').map(x=>x.trim().toLowerCase());const groupIds=arr(state.data.groups).filter(g=>wanted.includes(g.name.toLowerCase())).map(g=>g.id);try{await api('admin/users/bulk',{method:'POST',body:{action:'groups',userIds:[...state.adminUsersSelected],groupIds}});await loadAdminUsers();renderAdminUsers();}catch(e){toast(e.message,'error');}return;}
});

document.addEventListener('change',async event=>{
  if(event.target.matches('[data-user-role]')){try{const out=await api('admin/user',{method:'POST',body:{action:'role',userId:event.target.dataset.userRole,role:event.target.value}});const i=state.adminUsers.findIndex(u=>u.id===out.user.id);if(i>=0)state.adminUsers[i]=out.user;toast('Role updated.','success');}catch(e){toast(e.message,'error');}}
  if(event.target.matches('[data-admin-user-select]')){event.target.checked?state.adminUsersSelected.add(event.target.dataset.adminUserSelect):state.adminUsersSelected.delete(event.target.dataset.adminUserSelect);}
  if(event.target.id==='userCsv'){const file=event.target.files?.[0];if(!file)return;try{const rows=parseCsv(await file.text());const groups=arr(state.data.groups);const users=rows.map(r=>({name:r.name,email:r.email,role:r.role||'viewer',groupIds:String(r.groups||r.group||'').split(';').map(x=>x.trim().toLowerCase()).filter(Boolean).map(name=>groups.find(g=>g.name.toLowerCase()===name)?.id).filter(Boolean)}));const out=await api('admin/users/import',{method:'POST',body:{users}});toast(`${out.created} users invited; ${out.skipped} skipped.`,'success');await loadAdminUsers();renderAdminUsers();}catch(e){toast(e.message,'error');}}
  if(event.target.matches('[data-inline-resource]')){const file=event.target.files?.[0];if(!file)return;try{setLoading(true,'Uploading document…');const out=await api('learning/resource-upload',{method:'POST',body:{title:file.name,fileName:file.name,dataBase64:await fileToBase64(file),category:'Course upload'}});upsert('resources',out.resource);const card=event.target.closest('[data-module-card]');const select=$('[name=moduleResource]',card);select.insertAdjacentHTML('beforeend',`<option value="${out.resource.id}">${esc(out.resource.title)}</option>`);select.value=out.resource.id;toast('Document uploaded and selected.','success');}catch(e){toast(e.message,'error');}finally{setLoading(false);}}
});

document.addEventListener('input',event=>{if(event.target.closest('#editorForm')){state.dirty=true;const draft={};for(const el of $$('input,textarea,select',$('#editorForm'))){if(!el.name||el.type==='file'||el.name==='targetGroupIds')continue;draft[el.name]=el.type==='checkbox'?el.checked:el.value;}if(state.editor?.draftKey)localStorage.setItem(state.editor.draftKey,JSON.stringify(draft));}if(event.target.matches('[data-group-search]')){const q=event.target.value.toLowerCase();const groupBox=event.target.parentElement.querySelector('.groups-check');$$('label',groupBox).forEach(label=>label.classList.toggle('hidden',!label.textContent.toLowerCase().includes(q)));}});

document.addEventListener('submit',async event=>{
  if(event.target.id==='loginForm'){event.preventDefault();const fd=new FormData(event.target);$('#authMessage').textContent='';try{setLoading(true,'Signing in…');const out=await api('auth/login',{method:'POST',body:{email:fd.get('email'),password:fd.get('password')}});if(out.mfaRequired){showAuth('mfa');$('#mfaForm [name=challenge]').value=out.challenge;return;}await bootstrap({quiet:true});}catch(e){$('#authMessage').textContent=e.message;}finally{setLoading(false);}return;}
  if(event.target.id==='signupForm'){event.preventDefault();const fd=new FormData(event.target);if(fd.get('password')!==fd.get('confirm'))return $('#authMessage').textContent='Passwords do not match.';try{setLoading(true,'Creating account…');const out=await api('auth/signup',{method:'POST',body:{name:fd.get('name'),email:fd.get('email'),password:fd.get('password'),website:fd.get('website')}});$('#authMessage').textContent=out.message||'Account created. Check your email if verification is required.';if(out.signedIn)await bootstrap({quiet:true});else showAuth('login');}catch(e){$('#authMessage').textContent=e.message;}finally{setLoading(false);}return;}
  if(event.target.id==='resetForm'){event.preventDefault();const fd=new FormData(event.target);try{const out=await api('auth/request-reset',{method:'POST',body:{email:fd.get('email')}});$('#authMessage').textContent=out.message||'If the account exists, reset instructions are on the way.';}catch(e){$('#authMessage').textContent=e.message;}return;}
  if(event.target.id==='resetTokenForm'){event.preventDefault();const fd=new FormData(event.target);if(fd.get('password')!==fd.get('confirm'))return $('#authMessage').textContent='Passwords do not match.';try{const out=await api('auth/reset-password',{method:'POST',body:{email:fd.get('email'),token:fd.get('token'),password:fd.get('password')}});$('#authMessage').textContent=out.message||'Password updated.';history.replaceState({},'',location.pathname);showAuth('login');}catch(e){$('#authMessage').textContent=e.message;}return;}
  if(event.target.id==='mfaForm'){event.preventDefault();const fd=new FormData(event.target);try{await api('auth/mfa-login',{method:'POST',body:{challenge:fd.get('challenge'),code:fd.get('code')}});await bootstrap();}catch(e){$('#authMessage').textContent=e.message;}return;}
  if(event.target.id==='editorForm')return saveEditor(event);
  if(event.target.matches('[data-doc-feedback]')){event.preventDefault();const fd=new FormData(event.target);try{const out=await api('knowledge/comment',{method:'POST',body:{action:event.target.dataset.docFeedback,docId:event.target.dataset.id,text:fd.get('text')}});upsert('docs',out.item);openItem('docs',out.item.id);}catch(e){toast(e.message,'error');}return;}
  if(event.target.id==='quizForm')return submitQuiz(event);
  if(event.target.id==='adminActionForm')return submitAdminAction(event);
  if(event.target.id==='courseAdminForm')return submitCourseAdmin(event);
  if(event.target.id==='opsForm')return saveOps(event);
  if(event.target.id==='enableMfaForm'){event.preventDefault();const fd=new FormData(event.target);try{const out=await api('auth/mfa/enable',{method:'POST',body:{challenge:fd.get('challenge'),code:fd.get('code')}});state.data.me={...state.data.me,mfaEnabled:true};$('#securityModal').close();renderAll();toast('MFA enabled.','success');}catch(e){toast(e.message,'error');}return;}
  if(event.target.id==='disableMfaForm'){event.preventDefault();const fd=new FormData(event.target);try{const out=await api('auth/mfa/disable',{method:'POST',body:{password:fd.get('password'),code:fd.get('code')}});state.data.me={...state.data.me,mfaEnabled:false};$('#securityModal').close();renderAll();toast('MFA disabled.','success');}catch(e){toast(e.message,'error');}}
});

$$('[data-auth]').forEach(btn=>btn.addEventListener('click',()=>showAuth(btn.dataset.auth)));
$('#globalSearch').addEventListener('input',event=>{clearTimeout(searchTimer);const q=event.target.value;searchTimer=setTimeout(()=>doSearch(q),280);});
$('#quickCreate').addEventListener('click',()=>canEdit()?openEditor('updates'):setView('communications'));
$('#commBulkArchive').addEventListener('click',async()=>{const ids=$$('[data-select-comm]:checked').map(x=>x.dataset.selectComm);if(!ids.length)return toast('Select communications first.','error');try{await api('content/bulk',{method:'POST',body:{collection:'updates',ids,action:'archive'}});for(const id of ids){const x=find('updates',id);if(x)x.status='Archived';}renderCommunications();toast(`${ids.length} archived.`,'success');}catch(e){toast(e.message,'error');}});
$('#docBulkArchive').addEventListener('click',async()=>{const ids=$$('[data-select-doc]:checked').map(x=>x.dataset.selectDoc);if(!ids.length)return toast('Select knowledge items first.','error');try{await api('content/bulk',{method:'POST',body:{collection:'docs',ids,action:'archive'}});for(const id of ids){const x=find('docs',id);if(x)x.status='Archived';}renderKnowledge();toast(`${ids.length} archived.`,'success');}catch(e){toast(e.message,'error');}});
$('#editorModal').addEventListener('cancel',event=>{if(state.dirty){event.preventDefault();safeCloseEditor();}});$('#editorModal').addEventListener('click',event=>{if(event.target===$('#editorModal'))safeCloseEditor();});window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue='';}});
document.addEventListener('hub-offline',()=>setOffline(true));document.addEventListener('hub-online',()=>setOffline(false));document.addEventListener('hub-auth-expired',()=>{if(!$('#appShell').classList.contains('hidden')){toast('Your session expired. Please sign in again.','error');showAuth('login');}});

// 20-second revision polling gives near-real-time updates without keeping a websocket open.
setInterval(async()=>{if($('#appShell').classList.contains('hidden')||document.hidden)return;try{const out=await syncMeta();const previous=state.meta?.revisions||{},next=out.meta?.revisions||{};const changed=Object.keys(next).filter(k=>next[k]!==previous[k]);state.meta=out.meta||state.meta;if(changed.length){const scopes=[...new Set([...changed,'notifications'])].join(',');await refresh(scopes,{quiet:true});}else await refresh('notifications',{quiet:true});}catch{}},20000);

async function init(){applyTheme();initBrandAssets().catch(()=>{});if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const params=new URLSearchParams(location.search);if(params.has('verify')){showAuth('verify');try{const out=await api('auth/verify-email',{method:'POST',body:{email:params.get('email'),token:params.get('verify')}});$('#verifyMessage').textContent=out.message||'Email verified. You can sign in.';history.replaceState({},'',location.pathname);}catch(e){$('#verifyMessage').textContent=e.message;}return;}if(params.has('reset')){showAuth('resetToken');$('#resetTokenForm [name=email]').value=params.get('email')||'';$('#resetTokenForm [name=token]').value=params.get('reset')||'';return;}await bootstrap();if(isAdmin()){await loadAdminUsers();renderAdmin();}}
init();
