const state = { data: {updates:[],docs:[],decisions:[]}, view:'home', edit:null, filter:'all', accessCode: sessionStorage.getItem('teamAccessCode') || '' };
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const api = async (path='data', opts={}) => {
  const res = await fetch(`/api/${path}`, { ...opts, headers:{'content-type':'application/json','x-team-access-code':state.accessCode,...(opts.headers||{})} });
  if(res.status===401) throw new Error('ACCESS');
  if(!res.ok) throw new Error((await res.json()).error || 'Request failed');
  return res.json();
};
const fmt = d => d ? new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(d)) : 'No date';
const esc = s => String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
async function load(){try{state.data=await api();$('#accessGate').classList.add('hidden');render()}catch(e){if(e.message==='ACCESS'){$('#accessGate').classList.remove('hidden')}else toast(e.message)}}
function render(){renderStats();renderHome();renderUpdates();renderDocs();renderDecisions()}
function renderStats(){const due=[...state.data.updates,...state.data.docs,...state.data.decisions].filter(x=>x.reviewDate&&new Date(x.reviewDate)<new Date(Date.now()+14*864e5)).length;$('#stats').innerHTML=[['Active updates',state.data.updates.filter(x=>x.status==='Active').length],['Knowledge pages',state.data.docs.length],['Decisions',state.data.decisions.length],['Review soon',due]].map(([a,b])=>`<div class="stat"><strong>${b}</strong><span>${a}</span></div>`).join('')}
function renderHome(){const updates=[...state.data.updates].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5);$('#latestUpdates').innerHTML=updates.map(u=>row('updates',u.id,u.title,`${u.category} · ${fmt(u.createdAt)}`,u.priority)).join('')||empty('No updates yet.');const due=[...state.data.updates.map(x=>({...x,_c:'updates',_t:x.title})),...state.data.docs.map(x=>({...x,_c:'docs',_t:x.title})),...state.data.decisions.map(x=>({...x,_c:'decisions',_t:x.decision}))].filter(x=>x.reviewDate&&new Date(x.reviewDate)<new Date(Date.now()+14*864e5)).sort((a,b)=>new Date(a.reviewDate)-new Date(b.reviewDate)).slice(0,5);$('#reviewQueue').innerHTML=due.map(x=>row(x._c,x.id,x._t,`Review ${fmt(x.reviewDate)}`,x.status)).join('')||empty('Nothing due for review.');const docs=[...state.data.docs].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,3);$('#recentDocs').innerHTML=docs.map(docCard).join('')||empty('No knowledge pages yet.')}
function row(c,id,title,sub,badge){return `<div class="list-row" data-open="${c}" data-id="${id}"><div><strong>${esc(title)}</strong><small>${esc(sub)}</small></div><span class="pill ${String(badge||'').toLowerCase()}">${esc(badge||'')}</span></div>`}
function empty(t){return `<p class="muted">${esc(t)}</p>`}
function renderUpdates(){let items=[...state.data.updates].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));if(state.filter!=='all') items=items.filter(x=>x.priority===state.filter||x.status===state.filter);$('#updatesList').innerHTML=items.map(u=>`<article class="update-card" data-open="updates" data-id="${u.id}"><div class="date">${fmt(u.createdAt)}</div><div><div class="meta"><span>${esc(u.category)}</span><span>Owner: ${esc(u.owner)}</span></div><h3>${esc(u.title)}</h3><p>${esc(u.summary)}</p></div><div><span class="pill ${u.priority.toLowerCase()}">${esc(u.priority)}</span></div></article>`).join('')||empty('No updates match this filter.')}
function docCard(d){return `<article class="doc-card" data-open="docs" data-id="${d.id}"><div class="meta"><span class="pill">${esc(d.type)}</span><span>${fmt(d.updatedAt)}</span></div><h4>${esc(d.title)}</h4><p>${esc((d.content||'').slice(0,130))}${(d.content||'').length>130?'…':''}</p><div class="meta"><span>${esc(d.owner)}</span><span class="pill ${d.status.toLowerCase()}">${esc(d.status)}</span></div></article>`}
function renderDocs(){$('#docsGrid').innerHTML=[...state.data.docs].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).map(docCard).join('')||empty('No knowledge pages yet.')}
function renderDecisions(){$('#decisionsList').innerHTML=[...state.data.decisions].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(d=>`<article class="decision" data-open="decisions" data-id="${d.id}"><div class="meta"><span>${fmt(d.createdAt)}</span><span class="pill ${d.status.toLowerCase()}">${esc(d.status)}</span></div><h3>${esc(d.decision)}</h3><div class="cols"><div><strong>Why</strong><br>${esc(d.reason)}</div><div><strong>Impact</strong><br>${esc(d.impact)}</div></div><div class="meta" style="margin-top:14px"><span>Owner: ${esc(d.owner)}</span><span>${d.reviewDate?'Review '+fmt(d.reviewDate):''}</span></div></article>`).join('')||empty('No decisions recorded yet.')}
function setView(v){state.view=v;$$('.view').forEach(x=>x.classList.remove('active'));$(`#${v}View`).classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const titles={home:'What changed?',updates:'Updates',knowledge:'Knowledge',decisions:'Decisions',search:'Search'};$('#viewTitle').textContent=titles[v]||'Team Comms';$('#newItemBtn').textContent=v==='knowledge'?'+ New page':v==='decisions'?'+ Record decision':'+ New update'}
const fields = {
  updates:[['title','Title','text'],['summary','Summary','textarea'],['category','Category','select',['Announcement','Project Update','Operational Update','Decision','Process Change','Risk','Customer Update','Meeting Outcome']],['priority','Priority','select',['Critical','High','Medium','Low']],['owner','Owner','text'],['status','Status','select',['Draft','Active','Archived']],['reviewDate','Review date','date'],['link','Related link','url']],
  docs:[['title','Page title','text'],['content','Content','textarea'],['type','Type','select',['SOP','Reference','FAQ','Project','Meeting Notes']],['owner','Owner','text'],['status','Status','select',['Draft','Active','Archived']],['reviewDate','Review date','date']],
  decisions:[['decision','Decision','textarea'],['reason','Why this decision','textarea'],['impact','Impact / what changes','textarea'],['owner','Owner','text'],['status','Status','select',['Active','Superseded','Archived']],['reviewDate','Review date','date']]
};
function openEditor(collection,id=null){const item=id?state.data[collection].find(x=>x.id===id):{};state.edit={collection,id};$('#modalEyebrow').textContent=id?'EDIT':'NEW';$('#modalTitle').textContent=collection==='updates'?(id?'Edit update':'Create update'):collection==='docs'?(id?'Edit knowledge page':'Create knowledge page'):(id?'Edit decision':'Record decision');$('#deleteItem').style.visibility=id?'visible':'hidden';$('#formFields').innerHTML=fields[collection].map(([k,l,t,opts],i)=>{const val=item?.[k]||'';if(t==='textarea')return `<div class="field"><label>${l}</label><textarea name="${k}" ${i===0?'required':''}>${esc(val)}</textarea></div>`;if(t==='select')return `<div class="field"><label>${l}</label><select name="${k}">${opts.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('')}</select></div>`;return `<div class="field"><label>${l}</label><input name="${k}" type="${t}" value="${esc(val)}" ${i===0?'required':''}></div>`}).join('');$('#editorModal').showModal()}
async function saveEditor(e){e.preventDefault();const fd=new FormData(e.currentTarget);const item=Object.fromEntries(fd.entries());if(state.edit.id)item.id=state.edit.id;const method=state.edit.id?'PUT':'POST';const out=await api('item',{method,body:JSON.stringify({collection:state.edit.collection,item})});state.data=out.data;$('#editorModal').close();render();toast('Saved')}
async function removeEditor(){if(!state.edit.id||!confirm('Delete this item?'))return;const out=await api('item',{method:'DELETE',body:JSON.stringify({collection:state.edit.collection,id:state.edit.id})});state.data=out.data;$('#editorModal').close();render();toast('Deleted')}
function search(q){q=q.trim().toLowerCase();if(!q){setView('home');return}const results=[];state.data.updates.forEach(x=>{if(JSON.stringify(x).toLowerCase().includes(q))results.push({c:'updates',id:x.id,title:x.title,sub:x.summary})});state.data.docs.forEach(x=>{if(JSON.stringify(x).toLowerCase().includes(q))results.push({c:'docs',id:x.id,title:x.title,sub:x.content})});state.data.decisions.forEach(x=>{if(JSON.stringify(x).toLowerCase().includes(q))results.push({c:'decisions',id:x.id,title:x.decision,sub:x.reason})});$('#searchCount').textContent=`${results.length} found`;$('#searchResults').innerHTML=results.map(x=>row(x.c,x.id,x.title,(x.sub||'').slice(0,120),'Open')).join('')||empty('No matching content.');setView('search')}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);const jump=e.target.closest('[data-jump]');if(jump)setView(jump.dataset.jump);const create=e.target.closest('[data-create]');if(create)openEditor(create.dataset.create);const open=e.target.closest('[data-open]');if(open)openEditor(open.dataset.open,open.dataset.id);const chip=e.target.closest('.chip');if(chip){$$('.chip').forEach(x=>x.classList.remove('active'));chip.classList.add('active');state.filter=chip.dataset.filter;renderUpdates()}});
$('#newItemBtn').addEventListener('click',()=>openEditor(state.view==='knowledge'?'docs':state.view==='decisions'?'decisions':'updates'));$('#closeModal').onclick=()=>$('#editorModal').close();$('#cancelModal').onclick=()=>$('#editorModal').close();$('#deleteItem').onclick=removeEditor;$('#editorForm').addEventListener('submit',saveEditor);let timer;$('#globalSearch').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>search(e.target.value),160)});$('#accessForm').addEventListener('submit',async e=>{e.preventDefault();state.accessCode=$('#accessCode').value;sessionStorage.setItem('teamAccessCode',state.accessCode);$('#accessError').textContent='';try{await load()}catch{}});
load();
